// <auto-generated />
using System;
using HotelBooking.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBooking.Infrastructure.Migrations
{
    [DbContext(typeof(HotelBookingDbContext))]
    [Migration("20251116122249_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelBooking.Infrastructure.Tables.BookingDBEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndingDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("IX_Bookings_RoomId");

                    b.HasIndex("StartingDate", "EndingDate")
                        .HasDatabaseName("IX_Bookings_DateRange");

                    b.HasIndex("RoomId", "StartingDate", "EndingDate")
                        .HasDatabaseName("IX_Bookings_RoomId_DateRange");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2025, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndingDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = new Guid("33333333-3333-3333-3333-333333333333"),
                            StartingDate = new DateTime(2025, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0dcbc9c6-c37e-4ac6-bc3f-9aed741cbda7"),
                            CreationDate = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndingDate = new DateTime(2025, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            StartingDate = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HotelBooking.Infrastructure.Tables.HotelDBEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Hotels_Name");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Grand Plaza Hotel"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Seaside Resort"
                        });
                });

            modelBuilder.Entity("HotelBooking.Infrastructure.Tables.RoomDbEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Capacity")
                        .HasDatabaseName("IX_Rooms_Capacity");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("IX_Rooms_HotelId");

                    b.HasIndex("HotelId", "Capacity")
                        .HasDatabaseName("IX_Rooms_HotelId_Capacity");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Capacity = 2,
                            HotelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Number = 101,
                            Type = "Double"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Capacity = 2,
                            HotelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Number = 102,
                            Type = "Double"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Capacity = 2,
                            HotelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Number = 103,
                            Type = "Double"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Capacity = 2,
                            HotelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Number = 104,
                            Type = "Double"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Capacity = 2,
                            HotelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Number = 105,
                            Type = "Deluxe"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Capacity = 2,
                            HotelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Number = 106,
                            Type = "Deluxe"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Capacity = 1,
                            HotelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 201,
                            Type = "Single"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Capacity = 1,
                            HotelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 202,
                            Type = "Single"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Capacity = 2,
                            HotelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 203,
                            Type = "Double"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Capacity = 2,
                            HotelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 204,
                            Type = "Double"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Capacity = 2,
                            HotelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 205,
                            Type = "Double"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Capacity = 2,
                            HotelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 206,
                            Type = "Double"
                        });
                });

            modelBuilder.Entity("HotelBooking.Infrastructure.Tables.BookingDBEntity", b =>
                {
                    b.HasOne("HotelBooking.Infrastructure.Tables.RoomDbEntity", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelBooking.Infrastructure.Tables.RoomDbEntity", b =>
                {
                    b.HasOne("HotelBooking.Infrastructure.Tables.HotelDBEntity", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelBooking.Infrastructure.Tables.HotelDBEntity", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelBooking.Infrastructure.Tables.RoomDbEntity", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
